// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine_gcmessages.proto

public final class EngineGcmessages {
  private EngineGcmessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CEngineGotvSyncPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CEngineGotvSyncPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 match_id = 1;</code>
     */
    boolean hasMatchId();
    /**
     * <code>optional uint64 match_id = 1;</code>
     */
    long getMatchId();

    /**
     * <code>optional uint32 instance_id = 2;</code>
     */
    boolean hasInstanceId();
    /**
     * <code>optional uint32 instance_id = 2;</code>
     */
    int getInstanceId();

    /**
     * <code>optional uint32 signupfragment = 3;</code>
     */
    boolean hasSignupfragment();
    /**
     * <code>optional uint32 signupfragment = 3;</code>
     */
    int getSignupfragment();

    /**
     * <code>optional uint32 currentfragment = 4;</code>
     */
    boolean hasCurrentfragment();
    /**
     * <code>optional uint32 currentfragment = 4;</code>
     */
    int getCurrentfragment();

    /**
     * <code>optional float tickrate = 5;</code>
     */
    boolean hasTickrate();
    /**
     * <code>optional float tickrate = 5;</code>
     */
    float getTickrate();

    /**
     * <code>optional uint32 tick = 6;</code>
     */
    boolean hasTick();
    /**
     * <code>optional uint32 tick = 6;</code>
     */
    int getTick();

    /**
     * <code>optional float rtdelay = 8;</code>
     */
    boolean hasRtdelay();
    /**
     * <code>optional float rtdelay = 8;</code>
     */
    float getRtdelay();

    /**
     * <code>optional float rcvage = 9;</code>
     */
    boolean hasRcvage();
    /**
     * <code>optional float rcvage = 9;</code>
     */
    float getRcvage();

    /**
     * <code>optional float keyframe_interval = 10;</code>
     */
    boolean hasKeyframeInterval();
    /**
     * <code>optional float keyframe_interval = 10;</code>
     */
    float getKeyframeInterval();
  }
  /**
   * Protobuf type {@code CEngineGotvSyncPacket}
   */
  public  static final class CEngineGotvSyncPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CEngineGotvSyncPacket)
      CEngineGotvSyncPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CEngineGotvSyncPacket.newBuilder() to construct.
    private CEngineGotvSyncPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CEngineGotvSyncPacket() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CEngineGotvSyncPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              matchId_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              instanceId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              signupfragment_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              currentfragment_ = input.readUInt32();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              tickrate_ = input.readFloat();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              tick_ = input.readUInt32();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000040;
              rtdelay_ = input.readFloat();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000080;
              rcvage_ = input.readFloat();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000100;
              keyframeInterval_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EngineGcmessages.internal_static_CEngineGotvSyncPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EngineGcmessages.internal_static_CEngineGotvSyncPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EngineGcmessages.CEngineGotvSyncPacket.class, EngineGcmessages.CEngineGotvSyncPacket.Builder.class);
    }

    private int bitField0_;
    public static final int MATCH_ID_FIELD_NUMBER = 1;
    private long matchId_;
    /**
     * <code>optional uint64 match_id = 1;</code>
     */
    public boolean hasMatchId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 match_id = 1;</code>
     */
    public long getMatchId() {
      return matchId_;
    }

    public static final int INSTANCE_ID_FIELD_NUMBER = 2;
    private int instanceId_;
    /**
     * <code>optional uint32 instance_id = 2;</code>
     */
    public boolean hasInstanceId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 instance_id = 2;</code>
     */
    public int getInstanceId() {
      return instanceId_;
    }

    public static final int SIGNUPFRAGMENT_FIELD_NUMBER = 3;
    private int signupfragment_;
    /**
     * <code>optional uint32 signupfragment = 3;</code>
     */
    public boolean hasSignupfragment() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 signupfragment = 3;</code>
     */
    public int getSignupfragment() {
      return signupfragment_;
    }

    public static final int CURRENTFRAGMENT_FIELD_NUMBER = 4;
    private int currentfragment_;
    /**
     * <code>optional uint32 currentfragment = 4;</code>
     */
    public boolean hasCurrentfragment() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 currentfragment = 4;</code>
     */
    public int getCurrentfragment() {
      return currentfragment_;
    }

    public static final int TICKRATE_FIELD_NUMBER = 5;
    private float tickrate_;
    /**
     * <code>optional float tickrate = 5;</code>
     */
    public boolean hasTickrate() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional float tickrate = 5;</code>
     */
    public float getTickrate() {
      return tickrate_;
    }

    public static final int TICK_FIELD_NUMBER = 6;
    private int tick_;
    /**
     * <code>optional uint32 tick = 6;</code>
     */
    public boolean hasTick() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 tick = 6;</code>
     */
    public int getTick() {
      return tick_;
    }

    public static final int RTDELAY_FIELD_NUMBER = 8;
    private float rtdelay_;
    /**
     * <code>optional float rtdelay = 8;</code>
     */
    public boolean hasRtdelay() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional float rtdelay = 8;</code>
     */
    public float getRtdelay() {
      return rtdelay_;
    }

    public static final int RCVAGE_FIELD_NUMBER = 9;
    private float rcvage_;
    /**
     * <code>optional float rcvage = 9;</code>
     */
    public boolean hasRcvage() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional float rcvage = 9;</code>
     */
    public float getRcvage() {
      return rcvage_;
    }

    public static final int KEYFRAME_INTERVAL_FIELD_NUMBER = 10;
    private float keyframeInterval_;
    /**
     * <code>optional float keyframe_interval = 10;</code>
     */
    public boolean hasKeyframeInterval() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional float keyframe_interval = 10;</code>
     */
    public float getKeyframeInterval() {
      return keyframeInterval_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, matchId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, instanceId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, signupfragment_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, currentfragment_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFloat(5, tickrate_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt32(6, tick_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeFloat(8, rtdelay_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeFloat(9, rcvage_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeFloat(10, keyframeInterval_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, matchId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, instanceId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, signupfragment_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, currentfragment_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, tickrate_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, tick_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, rtdelay_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, rcvage_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, keyframeInterval_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EngineGcmessages.CEngineGotvSyncPacket)) {
        return super.equals(obj);
      }
      EngineGcmessages.CEngineGotvSyncPacket other = (EngineGcmessages.CEngineGotvSyncPacket) obj;

      if (hasMatchId() != other.hasMatchId()) return false;
      if (hasMatchId()) {
        if (getMatchId()
            != other.getMatchId()) return false;
      }
      if (hasInstanceId() != other.hasInstanceId()) return false;
      if (hasInstanceId()) {
        if (getInstanceId()
            != other.getInstanceId()) return false;
      }
      if (hasSignupfragment() != other.hasSignupfragment()) return false;
      if (hasSignupfragment()) {
        if (getSignupfragment()
            != other.getSignupfragment()) return false;
      }
      if (hasCurrentfragment() != other.hasCurrentfragment()) return false;
      if (hasCurrentfragment()) {
        if (getCurrentfragment()
            != other.getCurrentfragment()) return false;
      }
      if (hasTickrate() != other.hasTickrate()) return false;
      if (hasTickrate()) {
        if (java.lang.Float.floatToIntBits(getTickrate())
            != java.lang.Float.floatToIntBits(
                other.getTickrate())) return false;
      }
      if (hasTick() != other.hasTick()) return false;
      if (hasTick()) {
        if (getTick()
            != other.getTick()) return false;
      }
      if (hasRtdelay() != other.hasRtdelay()) return false;
      if (hasRtdelay()) {
        if (java.lang.Float.floatToIntBits(getRtdelay())
            != java.lang.Float.floatToIntBits(
                other.getRtdelay())) return false;
      }
      if (hasRcvage() != other.hasRcvage()) return false;
      if (hasRcvage()) {
        if (java.lang.Float.floatToIntBits(getRcvage())
            != java.lang.Float.floatToIntBits(
                other.getRcvage())) return false;
      }
      if (hasKeyframeInterval() != other.hasKeyframeInterval()) return false;
      if (hasKeyframeInterval()) {
        if (java.lang.Float.floatToIntBits(getKeyframeInterval())
            != java.lang.Float.floatToIntBits(
                other.getKeyframeInterval())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMatchId()) {
        hash = (37 * hash) + MATCH_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMatchId());
      }
      if (hasInstanceId()) {
        hash = (37 * hash) + INSTANCE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getInstanceId();
      }
      if (hasSignupfragment()) {
        hash = (37 * hash) + SIGNUPFRAGMENT_FIELD_NUMBER;
        hash = (53 * hash) + getSignupfragment();
      }
      if (hasCurrentfragment()) {
        hash = (37 * hash) + CURRENTFRAGMENT_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentfragment();
      }
      if (hasTickrate()) {
        hash = (37 * hash) + TICKRATE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getTickrate());
      }
      if (hasTick()) {
        hash = (37 * hash) + TICK_FIELD_NUMBER;
        hash = (53 * hash) + getTick();
      }
      if (hasRtdelay()) {
        hash = (37 * hash) + RTDELAY_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRtdelay());
      }
      if (hasRcvage()) {
        hash = (37 * hash) + RCVAGE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRcvage());
      }
      if (hasKeyframeInterval()) {
        hash = (37 * hash) + KEYFRAME_INTERVAL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getKeyframeInterval());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EngineGcmessages.CEngineGotvSyncPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EngineGcmessages.CEngineGotvSyncPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CEngineGotvSyncPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CEngineGotvSyncPacket)
        EngineGcmessages.CEngineGotvSyncPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EngineGcmessages.internal_static_CEngineGotvSyncPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EngineGcmessages.internal_static_CEngineGotvSyncPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EngineGcmessages.CEngineGotvSyncPacket.class, EngineGcmessages.CEngineGotvSyncPacket.Builder.class);
      }

      // Construct using EngineGcmessages.CEngineGotvSyncPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        matchId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        instanceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        signupfragment_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        currentfragment_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        tickrate_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        tick_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        rtdelay_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        rcvage_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        keyframeInterval_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EngineGcmessages.internal_static_CEngineGotvSyncPacket_descriptor;
      }

      @java.lang.Override
      public EngineGcmessages.CEngineGotvSyncPacket getDefaultInstanceForType() {
        return EngineGcmessages.CEngineGotvSyncPacket.getDefaultInstance();
      }

      @java.lang.Override
      public EngineGcmessages.CEngineGotvSyncPacket build() {
        EngineGcmessages.CEngineGotvSyncPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EngineGcmessages.CEngineGotvSyncPacket buildPartial() {
        EngineGcmessages.CEngineGotvSyncPacket result = new EngineGcmessages.CEngineGotvSyncPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.matchId_ = matchId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.instanceId_ = instanceId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.signupfragment_ = signupfragment_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.currentfragment_ = currentfragment_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.tickrate_ = tickrate_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.tick_ = tick_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.rtdelay_ = rtdelay_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.rcvage_ = rcvage_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.keyframeInterval_ = keyframeInterval_;
          to_bitField0_ |= 0x00000100;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EngineGcmessages.CEngineGotvSyncPacket) {
          return mergeFrom((EngineGcmessages.CEngineGotvSyncPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EngineGcmessages.CEngineGotvSyncPacket other) {
        if (other == EngineGcmessages.CEngineGotvSyncPacket.getDefaultInstance()) return this;
        if (other.hasMatchId()) {
          setMatchId(other.getMatchId());
        }
        if (other.hasInstanceId()) {
          setInstanceId(other.getInstanceId());
        }
        if (other.hasSignupfragment()) {
          setSignupfragment(other.getSignupfragment());
        }
        if (other.hasCurrentfragment()) {
          setCurrentfragment(other.getCurrentfragment());
        }
        if (other.hasTickrate()) {
          setTickrate(other.getTickrate());
        }
        if (other.hasTick()) {
          setTick(other.getTick());
        }
        if (other.hasRtdelay()) {
          setRtdelay(other.getRtdelay());
        }
        if (other.hasRcvage()) {
          setRcvage(other.getRcvage());
        }
        if (other.hasKeyframeInterval()) {
          setKeyframeInterval(other.getKeyframeInterval());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EngineGcmessages.CEngineGotvSyncPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EngineGcmessages.CEngineGotvSyncPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long matchId_ ;
      /**
       * <code>optional uint64 match_id = 1;</code>
       */
      public boolean hasMatchId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 match_id = 1;</code>
       */
      public long getMatchId() {
        return matchId_;
      }
      /**
       * <code>optional uint64 match_id = 1;</code>
       */
      public Builder setMatchId(long value) {
        bitField0_ |= 0x00000001;
        matchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 match_id = 1;</code>
       */
      public Builder clearMatchId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        matchId_ = 0L;
        onChanged();
        return this;
      }

      private int instanceId_ ;
      /**
       * <code>optional uint32 instance_id = 2;</code>
       */
      public boolean hasInstanceId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 instance_id = 2;</code>
       */
      public int getInstanceId() {
        return instanceId_;
      }
      /**
       * <code>optional uint32 instance_id = 2;</code>
       */
      public Builder setInstanceId(int value) {
        bitField0_ |= 0x00000002;
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 instance_id = 2;</code>
       */
      public Builder clearInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        instanceId_ = 0;
        onChanged();
        return this;
      }

      private int signupfragment_ ;
      /**
       * <code>optional uint32 signupfragment = 3;</code>
       */
      public boolean hasSignupfragment() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint32 signupfragment = 3;</code>
       */
      public int getSignupfragment() {
        return signupfragment_;
      }
      /**
       * <code>optional uint32 signupfragment = 3;</code>
       */
      public Builder setSignupfragment(int value) {
        bitField0_ |= 0x00000004;
        signupfragment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 signupfragment = 3;</code>
       */
      public Builder clearSignupfragment() {
        bitField0_ = (bitField0_ & ~0x00000004);
        signupfragment_ = 0;
        onChanged();
        return this;
      }

      private int currentfragment_ ;
      /**
       * <code>optional uint32 currentfragment = 4;</code>
       */
      public boolean hasCurrentfragment() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint32 currentfragment = 4;</code>
       */
      public int getCurrentfragment() {
        return currentfragment_;
      }
      /**
       * <code>optional uint32 currentfragment = 4;</code>
       */
      public Builder setCurrentfragment(int value) {
        bitField0_ |= 0x00000008;
        currentfragment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 currentfragment = 4;</code>
       */
      public Builder clearCurrentfragment() {
        bitField0_ = (bitField0_ & ~0x00000008);
        currentfragment_ = 0;
        onChanged();
        return this;
      }

      private float tickrate_ ;
      /**
       * <code>optional float tickrate = 5;</code>
       */
      public boolean hasTickrate() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional float tickrate = 5;</code>
       */
      public float getTickrate() {
        return tickrate_;
      }
      /**
       * <code>optional float tickrate = 5;</code>
       */
      public Builder setTickrate(float value) {
        bitField0_ |= 0x00000010;
        tickrate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float tickrate = 5;</code>
       */
      public Builder clearTickrate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tickrate_ = 0F;
        onChanged();
        return this;
      }

      private int tick_ ;
      /**
       * <code>optional uint32 tick = 6;</code>
       */
      public boolean hasTick() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint32 tick = 6;</code>
       */
      public int getTick() {
        return tick_;
      }
      /**
       * <code>optional uint32 tick = 6;</code>
       */
      public Builder setTick(int value) {
        bitField0_ |= 0x00000020;
        tick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 tick = 6;</code>
       */
      public Builder clearTick() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tick_ = 0;
        onChanged();
        return this;
      }

      private float rtdelay_ ;
      /**
       * <code>optional float rtdelay = 8;</code>
       */
      public boolean hasRtdelay() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional float rtdelay = 8;</code>
       */
      public float getRtdelay() {
        return rtdelay_;
      }
      /**
       * <code>optional float rtdelay = 8;</code>
       */
      public Builder setRtdelay(float value) {
        bitField0_ |= 0x00000040;
        rtdelay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float rtdelay = 8;</code>
       */
      public Builder clearRtdelay() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rtdelay_ = 0F;
        onChanged();
        return this;
      }

      private float rcvage_ ;
      /**
       * <code>optional float rcvage = 9;</code>
       */
      public boolean hasRcvage() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional float rcvage = 9;</code>
       */
      public float getRcvage() {
        return rcvage_;
      }
      /**
       * <code>optional float rcvage = 9;</code>
       */
      public Builder setRcvage(float value) {
        bitField0_ |= 0x00000080;
        rcvage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float rcvage = 9;</code>
       */
      public Builder clearRcvage() {
        bitField0_ = (bitField0_ & ~0x00000080);
        rcvage_ = 0F;
        onChanged();
        return this;
      }

      private float keyframeInterval_ ;
      /**
       * <code>optional float keyframe_interval = 10;</code>
       */
      public boolean hasKeyframeInterval() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional float keyframe_interval = 10;</code>
       */
      public float getKeyframeInterval() {
        return keyframeInterval_;
      }
      /**
       * <code>optional float keyframe_interval = 10;</code>
       */
      public Builder setKeyframeInterval(float value) {
        bitField0_ |= 0x00000100;
        keyframeInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float keyframe_interval = 10;</code>
       */
      public Builder clearKeyframeInterval() {
        bitField0_ = (bitField0_ & ~0x00000100);
        keyframeInterval_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CEngineGotvSyncPacket)
    }

    // @@protoc_insertion_point(class_scope:CEngineGotvSyncPacket)
    private static final EngineGcmessages.CEngineGotvSyncPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EngineGcmessages.CEngineGotvSyncPacket();
    }

    public static EngineGcmessages.CEngineGotvSyncPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CEngineGotvSyncPacket>
        PARSER = new com.google.protobuf.AbstractParser<CEngineGotvSyncPacket>() {
      @java.lang.Override
      public CEngineGotvSyncPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CEngineGotvSyncPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CEngineGotvSyncPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CEngineGotvSyncPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EngineGcmessages.CEngineGotvSyncPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CEngineGotvSyncPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CEngineGotvSyncPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027engine_gcmessages.proto\032 google/protob" +
      "uf/descriptor.proto\"\313\001\n\025CEngineGotvSyncP" +
      "acket\022\020\n\010match_id\030\001 \001(\004\022\023\n\013instance_id\030\002" +
      " \001(\r\022\026\n\016signupfragment\030\003 \001(\r\022\027\n\017currentf" +
      "ragment\030\004 \001(\r\022\020\n\010tickrate\030\005 \001(\002\022\014\n\004tick\030" +
      "\006 \001(\r\022\017\n\007rtdelay\030\010 \001(\002\022\016\n\006rcvage\030\t \001(\002\022\031" +
      "\n\021keyframe_interval\030\n \001(\002B\003\200\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_CEngineGotvSyncPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CEngineGotvSyncPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CEngineGotvSyncPacket_descriptor,
        new java.lang.String[] { "MatchId", "InstanceId", "Signupfragment", "Currentfragment", "Tickrate", "Tick", "Rtdelay", "Rcvage", "KeyframeInterval", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
